services: 
  db:
    container_name: mariadb
    image: mariadb:11.2.2-jammy
    restart: always
    ports:
      - 3307:3307
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MYSQL_TCP_PORT: ${DB_PORT}
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql/

  api:
    container_name: api-node    
    build: .
    environment:
      NODE_ENV: development
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    image: ghcr.io/alexispet/final-test-slupshi/api:develop
    ports:
      - 3000:3000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    command: --interval 30 --label-enable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: toto@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: slupshi@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
      


