services: 
  db-prod:
    container_name: MariaDB
    image: mariadb:11.2.2-jammy
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD_PROD}
      MARIADB_USER: ${DB_USER_PROD}
      MARIADB_PASSWORD: ${DB_PASSWORD_PROD}
      MARIADB_DATABASE: ${DB_DATABASE_PROD}
      MYSQL_TCP_PORT: ${DB_PORT_PROD}
    volumes:
      - ./docker/prod/mariadb/data:/var/lib/mysql/
    # networks:
    #   - proxy

  api-prod:
    container_name: API-Node
    build: .
    environment:
      NODE_ENV: production
      DB_HOST: ${DB_HOST_PROD}
      DB_USER: ${DB_USER_PROD}
      DB_PASSWORD: ${DB_PASSWORD_PROD}
      DB_DATABASE: ${DB_DATABASE_PROD}
      DB_PORT: ${DB_PORT_PROD}
    depends_on:
      - db-prod
    image: ghcr.io/alexispet/final-test-slupshi/api:latest
    ports:
      - 80:3000
    # expose:
    #   - 80
    # labels:
    #   - "traefik.docker.network=proxy"
    #   - "traefik.enable=true"
    #   - "traefik.basic.port=80"
    #   - "traefik.basic.protocol=http"
    #   - "traefik.basic.protocol=https"
    #   - "traefik.basic.port=443"
    #   - "traefik.basic.frontend.rule=Host:slupshi.alpex.ovh"
    #   - "com.centurylinklabs.watchtower.enable=true"
    #   - "com.centurylinklabs.watchtower.scope=prod"    
    # networks:
    #   - proxy

  watchtower-prod:
    container_name: Watchtower
    image: containrrr/watchtower
    command: --interval 30 --label-enable --scope prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: "discord://${DISCORD_TOKEN}@${DISCORD_ID}"
      WATCHTOWER_NOTIFICATION_TEMPLATE: |-
        {{range .}}{{.Time.Format "12-01-2020 15:04:05"}} ({{.Level}})':' {{.Message}}{{println}}{{end}}    
    labels:
      - "com.centurylinklabs.watchtower.scope=prod"  
    # networks:
    #   - proxy

  # Problème de bad gateway avec Traefik
  
  # traefik:
  #   image: traefik:v1.7
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   networks:
  #     - proxy
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /opt/traefik/traefik.toml:/traefik.toml
  #     - /opt/traefik/acme.json:/acme.json
  #   container_name: traefik

networks:
  proxy:
    external: true
      


