services: 
  api:
    container_name: api-node
    build:
      context: .
      target: api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    depends_on:
      - db
    ports:
      - 3000:3000

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - 3036:3036
    environment:
      MARIADB_ROOT_PASSWORD: toto
      MARIADB_USER: toto
      MARIADB_PASSWORD: toto
      MARIADB_DATABASE: totoDb
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql/
  
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
      


