services: 
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD_PROD}
      MARIADB_USER: ${DB_USER_PROD}
      MARIADB_PASSWORD: ${DB_PASSWORD_PROD}
      MARIADB_DATABASE: ${DB_DATABASE_PROD}
      MYSQL_TCP_PORT: ${DB_PORT_PROD}
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql/

  api:
    container_name: api-node
    env_file: .env
    build:
      context: .
      target: api
    environment:
      NODE_ENV: production
    depends_on:
      - db
    image: ghcr.io/alexispet/final-test-slupshi/api:latest
    ports:
      - 80:80 
  
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
      


