services: 
  db-prod:
    container_name: MariaDB
    image: mariadb:11.2.2-jammy
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD_PROD}
      MARIADB_USER: ${DB_USER_PROD}
      MARIADB_PASSWORD: ${DB_PASSWORD_PROD}
      MARIADB_DATABASE: ${DB_DATABASE_PROD}
      MYSQL_TCP_PORT: ${DB_PORT_PROD}
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql/

  api-prod:
    container_name: API Node
    build: .
    environment:
      NODE_ENV: production
      DB_HOST: ${DB_HOST_PROD}
      DB_USER: ${DB_USER_PROD}
      DB_PASSWORD: ${DB_PASSWORD_PROD}
      DB_DATABASE: ${DB_DATABASE_PROD}
      DB_PORT: ${DB_PORT_PROD}
    depends_on:
      - db-prod
    image: ghcr.io/alexispet/final-test-slupshi/api:latest
    ports:
      - 80:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower-prod:
    container_name: Watchtower
    image: containrrr/watchtower
    command: --interval 30 --label-enable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: "discord://${DISCORD_TOKEN}@${DISCORD_ID}"
      WATCHTOWER_NOTIFICATION_TEMPLATE: |-
        {{range .}}{{.Time.Format "12-01-2020 15:04:05"}} ({{.Level}})':' {{.Message}}{{println}}{{end}}
      


