services: 
  db:
    container_name: mariadb
    image: mariadb:11.2.2-jammy
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MYSQL_TCP_PORT: ${DB_PORT}
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql/

  api:
    container_name: api-node    
    build: 
      context: .
      target: api
    env_file: .env
    depends_on:
      - db
    image: ghcr.io/alexispet/final-test-slupshi/api:develop
    ports:
      - 3000:3000
      


